import {
  Pet,
  User,
  Post,
  CalendarEvent,
  Notification,
  AiMessage,
  DiaryEntry,
} from '../types';

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Sarah',
  email: 'sarah@example.com',
  avatarUrl: undefined,
};

export const MOCK_PETS: Pet[] = [
  {
    id: 'p1',
    name: 'Bella',
    species: 'dog',
    breed: 'Beagle',
    age: 3,
    weightKg: 10.5,
    heightCm: 38,
    gender: 'female',
    photoUrl: undefined,
    traits: ['High Energy', 'Friendly'],
    status: 'healthy',
    statusLabel: 'Healthy',
    nextEvent: 'Next Grooming: June 12',
    weightGoalPercent: 85,
  },
  {
    id: 'p2',
    name: 'Oliver',
    species: 'cat',
    breed: 'Domestic Shorthair',
    age: 5,
    weightKg: 4.2,
    heightCm: 25,
    gender: 'male',
    photoUrl: undefined,
    traits: ['Cuddly', 'Quiet'],
    status: 'due_for_vaccine',
    statusLabel: 'Due for vaccine',
    nextEvent: 'Health check: Overdue',
    weightGoalPercent: 40,
  },
  {
    id: 'p3',
    name: 'Luna',
    species: 'dog',
    breed: 'Frenchie',
    age: 1,
    weightKg: 8.0,
    heightCm: 30,
    gender: 'female',
    photoUrl: undefined,
    traits: ['Playful', 'Adaptable'],
    status: 'healthy',
    statusLabel: 'Healthy',
    nextEvent: 'Weight goal: 95% met',
    weightGoalPercent: 95,
  },
];


export const MOCK_POSTS: Post[] = [
  {
    id: 'post1',
    author: 'Alice & Cooper',
    authorAvatarUrl: 'https://i.pravatar.cc/100?img=47',
    content:
      "Cooper found his favorite spot in the sun today. There's nothing like a lazy Sunday afternoon snooze. ☀️🐕",
    imageUrl: 'https://picsum.photos/seed/dog1/600/400',
    hashtags: ['#SundayVibes', '#GoldenRetriever'],
    likes: 124,
    comments: 18,
    timeAgo: '2 hours ago',
  },
  {
    id: 'post2',
    author: 'Mark K.',
    authorAvatarUrl: 'https://i.pravatar.cc/100?img=12',
    content:
      '"Just a reminder: Your pet doesn\'t care about your bad day, they just care that you\'re home. Give them an extra treat today! 🐾"',
    hashtags: [],
    likes: 342,
    comments: 45,
    timeAgo: '5 hours ago',
  },
  {
    id: 'post3',
    author: "Sarah's Zoo",
    authorAvatarUrl: 'https://i.pravatar.cc/100?img=23',
    content:
      "New member alert! Meet Oliver. He's a bit shy but already loves the organic treats from Kindred Shop. 🐰 🌿",
    imageUrl: 'https://picsum.photos/seed/cat1/600/400',
    hashtags: ['#NewMember', '#AdoptDontShop'],
    likes: 89,
    comments: 12,
    timeAgo: 'Today',
  },
];

export const MOCK_EVENTS: CalendarEvent[] = [
  {
    id: 'e1',
    title: 'Vet Appointment',
    description: 'Annual vaccinations for Bella',
    time: '10:30 AM',
    allDay: false,
    category: 'vet',
    petId: 'p1',
    done: false,
    date: '2026-06-07',
    repeat: 'none',
  },
  {
    id: 'e2',
    title: 'Heartworm Medication',
    description: 'Monthly dose for Oliver',
    time: '08:00 AM',
    allDay: false,
    category: 'medication',
    petId: 'p2',
    done: true,
    date: '2026-06-07',
    repeat: 'monthly',
    recurringId: 'r001',
  },
  {
    id: 'e3',
    title: 'Grooming',
    description: 'Full wash and trim at Paws Spa',
    time: '02:15 PM',
    allDay: false,
    category: 'grooming',
    petId: 'p1',
    done: false,
    date: '2026-06-07',
    repeat: 'none',
  },
  {
    id: 'e4',
    title: 'Park Visit',
    description: 'Socialization playdate',
    time: '04:00 PM',
    allDay: false,
    category: 'activity',
    petId: 'p3',
    done: false,
    date: '2026-06-08',
    repeat: 'weekly',
    recurringId: 'r002',
  },
  {
    id: 'e5',
    title: 'Morning Walk',
    description: '',
    time: '',
    allDay: true,
    category: 'activity',
    petId: 'all',
    done: false,
    date: '2026-06-10',
    repeat: 'none',
  },
];


export const MOCK_DIARY_ENTRIES: DiaryEntry[] = [
  {
    id: 'd1',
    petId: 'p1',
    date: '2026-06-06',
    photoUrl: 'https://picsum.photos/seed/dog1/400/400',
    photos: [
      { url: 'https://picsum.photos/seed/dog1/400/400', time: '10:24 AM' },
      { url: 'https://picsum.photos/seed/cat1/400/400', time: '2:15 PM' },
    ],
    title: 'Adventure in the Park',
    note: "Today was absolutely wonderful! Bella met a new friend at the local park, a very energetic beagle. They chased each other for nearly an hour. Later, Bella found a sunny spot by the window for her afternoon nap. She's been so much more relaxed lately.",
    mood: ['happy', 'playful', 'sunny'],
    hashtags: ['#parkday', '#energyboost', '#naplife'],
    entryNumber: 142,
  },
  {
    id: 'd2',
    petId: 'p1',
    date: '2026-06-05',
    photoUrl: 'https://picsum.photos/seed/dog2/400/400',
    photos: [{ url: 'https://picsum.photos/seed/dog2/400/400', time: '9:00 AM' }],
    title: 'Morning Walk',
    note: 'Short but refreshing morning walk around the neighbourhood.',
    mood: ['happy'],
    hashtags: ['#morningwalk', '#freshair'],
    entryNumber: 141,
  },
  {
    id: 'd3',
    petId: 'p1',
    date: '2026-06-04',
    photoUrl: 'https://picsum.photos/seed/dog3/400/400',
    photos: [{ url: 'https://picsum.photos/seed/dog3/400/400', time: '3:00 PM' }],
    title: 'New Treats Day',
    note: 'Tried the new organic treats. She loved them! Finished the whole bag faster than expected.',
    mood: ['happy', 'playful'],
    hashtags: ['#organictreats', '#yummy'],
    entryNumber: 140,
  },
  {
    id: 'd4',
    petId: 'p1',
    date: '2026-06-03',
    photoUrl: 'https://picsum.photos/seed/dog4/400/400',
    photos: [{ url: 'https://picsum.photos/seed/dog4/400/400', time: '11:30 AM' }],
    title: 'Cozy Indoor Day',
    note: 'Rainy day so we stayed indoors. Lots of cuddles on the couch.',
    mood: ['sleepy'],
    hashtags: ['#rainyday', '#cozy'],
    entryNumber: 139,
  },
  {
    id: 'd5',
    petId: 'p1',
    date: '2026-06-02',
    photoUrl: 'https://picsum.photos/seed/dog5/400/400',
    photos: [
      { url: 'https://picsum.photos/seed/dog5/400/400', time: '4:00 PM' },
      { url: 'https://picsum.photos/seed/bird1/400/400', time: '5:30 PM' },
    ],
    title: 'Playdate!',
    note: 'Park day with friends! Bella had the best time running around.',
    mood: ['happy', 'playful'],
    hashtags: ['#playdate', '#fun'],
    entryNumber: 138,
  },
  {
    id: 'd6',
    petId: 'p1',
    date: '2026-06-01',
    photoUrl: 'https://picsum.photos/seed/dog6/400/400',
    photos: [{ url: 'https://picsum.photos/seed/dog6/400/400', time: '8:00 AM' }],
    title: 'Hello June',
    note: 'First day of June! Starting the month strong with a long walk.',
    mood: ['sunny'],
    hashtags: ['#june', '#newmonth'],
    entryNumber: 137,
  },
];

export const MOCK_AI_MESSAGES: AiMessage[] = [
  {
    id: 'm1',
    role: 'assistant',
    content:
      "Hi! I'm Kindred AI. You can snap a photo of your pet or ask me anything about their health, diet, or behaviour.",
    timestamp: '10:00 AM',
  },
];
